apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: hydroponics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
