---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend-deployment
  namespace: hydroponics
  labels:
    app: flask-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: flask-app-container
        image: gmangione/frontend-app:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_API_URL
          value: "http://reader-api-service:5001/"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-service
  namespace: hydroponics
spec:
  type: NodePort 
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 5000 
    nodePort: 30090 
  selector:
    app: flask-frontend

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: hydroponics
spec:
  serviceName: "mongodb-headless-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: local-pvc  

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
  namespace: hydroponics
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None
