apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-lb
  namespace: hydroponics
spec:
  type: LoadBalancer
  loadBalancerIP: 10.66.250.145  # IP de MetalLB dentro del rango definido
  selector:
    app: flask-frontend
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
