---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend-deployment 
  labels:
    app: flask-frontend 

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: flask-frontend 
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: flask-app-container
        image: agusolivares/mi-app:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000 
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-service 
spec:
  type: NodePort
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 5000 
    nodePort: 30080
  selector:
    app: flask-frontend 


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb-headless-service" 
  replicas: 3 
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db 
  volumeClaimTemplates: 
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi 
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None 
