FROM python:3.9-slim-buster


WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .


#Seteo app.py como el punto de entrada de la app Flask
ENV FLASK_APP=app.py


EXPOSE 5000


CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]

