apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: hydroponics
data:
  mosquitto.conf: |
    # Mosquitto MQTT Broker Configuration
    persistence true
    persistence_location /mosquitto/data/
    
    # Logging
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
    
    # Network settings
    listener 1883
    protocol mqtt
    
    # WebSocket support
    listener 9001
    protocol websockets
    
    # Security settings
    allow_anonymous true
    
    # Connection settings
    max_connections 1000
    max_inflight_messages 100
    max_queued_messages 1000
    
    # Message size limits
    message_size_limit 10485760
    
    # Persistence settings
    autosave_interval 1800
    autosave_on_changes false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: hydroponics
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 9001
          name: websocket
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config
        - name: mosquitto-data
          mountPath: /mosquitto/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: hydroponics
spec:
  selector:
    app: mosquitto
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: mqtt
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: websocket
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-external
  namespace: hydroponics
spec:
  selector:
    app: mosquitto
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
    nodePort: 31883
  type: NodePort
